// @ts-check

/** @type {import('prettier').Config & import('prettier-plugin-tailwindcss').PluginOptions & import('@ianvs/prettier-plugin-sort-imports').PluginConfig} */
export default {
  semi: false,
  arrowParens: 'always',
  trailingComma: 'all',
  bracketSameLine: false,
  bracketSpacing: true,
  experimentalTernaries: false,
  singleQuote: true,
  jsxSingleQuote: true,
  quoteProps: 'as-needed',
  singleAttributePerLine: true,
  htmlWhitespaceSensitivity: 'css',
  vueIndentScriptAndStyle: false,
  proseWrap: 'preserve',
  insertPragma: false,
  printWidth: 80,
  requirePragma: false,
  tabWidth: 2,
  useTabs: false,
  embeddedLanguageFormatting: 'auto',
  importOrder: [
    '^react',
    '<THIRD_PARTY_MODULES>',
    '',
    '.s?css$',
    '^lucide-react',
    '^@icons-pack',
    '^@heroicons',
    '^@/assets',
    '',
    '^[./]',
    '^@/',
    '',
    '<TYPES>^[./]',
    '<TYPES>^react',
    '<TYPES>^@/',
    '<TYPES>',
  ],
  importOrderTypeScriptVersion: '5.0.0',
  tailwindConfig: './tailwind.config.mjs',
  plugins: [
    '@ianvs/prettier-plugin-sort-imports',
    'prettier-plugin-tailwindcss',
  ],
}
